# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: sonatype-nexus-staging
        server-username: ${{ secrets.OSSRH_USER }}
        server-password: ${{ secrets.OSSRH_PASSWORD }}
        gpg-passphrase: ${{ secrets.GPG_PASSWORD }}
    - name: Publish to Maven Central Repo
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.GPG_SECRET }}
        gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
        nexus_username: ${{ secrets.OSSRH_USER }}
        nexus_password: ${{ secrets.OSSRH_PASSWORD }}
